# This is a basic workflow to help you get started with Actions

name: Mirror

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 2 * * 0-6"
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - run: git config remote.origin.mirror true
      - run: git remote add --mirror=fetch netfilter git://git.netfilter.org/iptables
      - run: git fetch netfilter
      - run: git push --mirror origin
